name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # 必要に応じてバージョンを変更
      
      - name: start hardhat node
        run: npx hardhat node
        working-directory: ./contracts

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
